version: "3.3"
services:
  db:
    image: postgis/postgis
    container_name: hackaton_db
    environment:
       - POSTGRES_USER=myuser
       - POSTGRES_PASSWORD=mypass
       - POSTGRES_DB=appnamedb
       - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgis/data

  backend:
     depends_on:
       - db
     image: starter:latest
     build:
       context: ./
     environment:
       - POSTGRES_DB
       - POSTGRES_USER
       - POSTGRES_PASSWORD
       - DB_HOST
     ports:
       - 8080:8080
volumes:
    pg-data:
     