version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: hackathon_db
    environment:
      - POSTGRES_DB=hackathon_dev
      - POSTGRES_USER=hackathon_user
      - POSTGRES_PASSWORD=hackathon_pass
    ports:
      - 5431:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: hackathon/project:latest
    build:
      context: ./
    environment:
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
    ports:
      - 8080:8080

volumes:
  pg-data:
